### ISSUE TITLE
Uses code for a project

### ISSUE THREAD

**Issue by Chucktheduck404** [aws/aws-iot-device-sdk-js#137] opened 2017-07-23 22:26 UTC
Im working on a self watering plant system. Link here https://www.hackster.io/demirhanaydin/waterpi-houseplant-remote-watering-and-monitoring-system-340400. I followed all the steps and have modifed the code slightly for my lcd to work. I keep running into this error and I'm not sure how to fix it. Any help would be appreciated.

events.js:141
throw er; // Unhandled 'error' event
^

Error: getaddrinfo ENOTFOUND a2paxuwr910.iot.us-west-2.amazonaws.com a2paxuwr910oz.iot.us-west-2.amazonaws.com:883
at errnoException (dns.js:26:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by fengsongAWS** [comment] 2017-07-24 16:56
This error is caused by node js cannot find the correct host. 
Could you first checkout if you can run the sample successfully with your certs and CA? This is to make sure we have the correct configuration for your local devices connection to AWS IoT.
Secondly, another cause of this could be your internet is not stable and this error is not properly cached. You can refer to this https://github.com/aws/aws-iot-device-sdk-js/issues/130 and see if it helps you solve the issue.

Thanks

**Comment by Chucktheduck404** [comment] 2017-07-24 19:28
Thanks I tried your fix but i'm still having a problem connecting to the host. https://github.com/demirhanaydin/waterpi-node/blob/master/device.js#L4-L7. Here are the lines I updated the paths are all correct but im guessing theres something that i need to do with my host. I didn't put the http in as that is a problem for some.

**Comment by fengsongAWS** [comment] 2017-07-24 20:01
How often do you experience this problem? Are you always seeing this issue each time you connect to IoT? Normally, you do need to care about http prefix. Did you successfully run the sample? 
BTW, I saw the port you are trying to connect is 883. Is this a copy paste error or you are connecting to the wrong port which is supposed to be 8883.
As I mentioned before, this could possibly due to the flaky network. The change you make is to throw this error and therefore you can catch it or choose to retry or suppress.

**Comment by Chucktheduck404** [comment] 2017-07-24 20:36
I experience the problem every time that i try to connect one time yesterday it worked briefly and then threw the error but this was before I added the code. The port i'm using is 8883. It is probably an issue with my wifi because i implanted a static ip that may not be working to well but I can ping google. I also haven't tried to run the sample yet. I will attempt that next. The error also throws immediately usually even with the code I added which is strange. I did notice that my dns.js errors are slightly different then the forum you linked to me. Could this be part of the problem? Thanks for looking into my problem. I appreciate it.

**Comment by fengsongAWS** [comment] 2017-07-24 20:52
I would suggest try running the sample within the same environment and see if you still have issues. Sometimes misconfiguration like region, host, port number could also cause the similar problem. 
Then I would suggest to try with a different network environment both for the sample and your project to see if the error persists. 
If this is due to the network problem, you can catch the error and do something like clear-wait-retry.

**Comment by fengsongAWS** [comment] 2017-11-06 23:11
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Closed by fengsongAWS** 2017-11-06 23:11 UTC
