### ISSUE TITLE
ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by darylrobbins** [aws/aws-iot-device-sdk-js#41] opened 2016-03-06 19:52 UTC
The latest change has caused the SDK to cease working on my device due to the use of the ES6 Map type:

```
ERROR:    var activeSubscriptions = new Map();                                                                                                                                                    
   ERROR:                               ^                                                                                                                                                         
ERROR: ReferenceError: Map is not defined                                                                                                                                                         
    at new DeviceClient (/home/root/.node_app_slot/node_modules/aws-iot-device-sdk/device/index.js:232:34)                                                                                        
    at Object.DeviceClient [as device] (/home/root/.node_app_slot/node_modules/aws-iot-device-sdk/device/index.js:164:14)                                                                         
    at Object.<anonymous> (/home/root/.node_app_slot/main.js:11:21)                                                                                                                               
    at Module._compile (module.js:456:26)                                                                                                                                                         
    at Object.Module._extensions..js (module.js:474:10)                                                                                                                                           
    at Module.load (module.js:356:32)                                                                                                                                                             
    at Function.Module._load (module.js:312:12)                                                                                                                                                   
    at Function.Module.runMain (module.js:497:10)                                                                                                                                                 
    at startup (node.js:119:16)                                                                                                                                                                   
    at node.js:935:3     
```

**Comment by gkwicker** [comment] 2016-03-07 16:51
Hi Daryl,

What version of Node.js are you running, and on which platform?  As a quick test, try running node with the '--harmony' option to enable staged features, e.g.:

```sh
node --harmony <program> <options>
```
You can see which language options are available as staged features by doing:

```sh
node --v8-options | grep harmony
```
If possible, you can also update your node installation to a later version which includes ES6 support.  Let us know if any of these suggestions help fix the problem, and thanks for using AWS IoT.

**Comment by peterpajchl** [comment] 2016-03-08 00:16
Hi,

got the same error on Ardunion Yun running Linino which comes with the Nodejs package unfortunately only in version **v0.10.25**.

But as suggested running a script with the `--harmony flag` does work fine as the new collections are part of that.

`--harmony_collections (enable harmony collections (sets, maps, and weak maps))`

**Comment by gkwicker** [comment] 2016-03-08 00:47
Hi Peter, thanks for letting us know; this is really helpful if other users encounter the same issue.  Thanks for using AWS IoT.

**Comment by hspaaij** [comment] 2016-03-12 07:35
Hi, got the same error when trying to use it to post a message from AWS Lambda. Lambda node.js doesn't support ES6 yet unfortunately.

**Comment by wkoffel** [comment] 2016-03-14 17:29
I too needed to run with `--harmony` with this latest version.  I realized in my case, there was some path confusion.  I had node5 installed at a user level, but when running under `sudo -u user`, it was picking up an older version of node (v0.10.29) which needed -harmony to be passed.

**Comment by thrundi** [comment] 2016-03-14 22:39
I got same error with Intel Galileo (node v0.10.38). Harmony flag doesn't seem to help for me.

**Comment by gkwicker** [comment] 2016-03-15 00:04
Hi everyone,

We're sorry about the issues caused by the use of ES6 types in the latest release; we will most likely remove these in the next release to eliminate this problem altogether.  In the meantime, if you're not able to resolve this using the `--harmony` flag, you might try using the babel transpiler to get access to ES6 features in a non-ES6 environment.  [This blog post](http://www.rricard.me/es6/aws/lambda/nodejs/2015/11/29/es6-on-aws-lambda.html) shows one way of doing it.  We're sorry for any confusion that this has caused, and thanks for using AWS IoT.

**Comment by davecrumbacher** [comment] 2016-03-16 16:37
I too am having this problem, in fact in the AWS environment.  I'm trying to write a NodeJS Lambda function to simulate data being pushed into the IoT environment.  However, the version of NodeJS running in Lambda is [0.10.36](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html), and thus it fails with the "ReferenceError: Map is not defined" error.  Therefore, I'm interested in the update you refer to.  Thanks.

**Comment by gkwicker** [comment] 2016-03-16 16:44
Hi Dave,

If you're only publishing data to AWS IoT from your Lambda function, the [AWS SDK for JavaScript](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/) has a [publish method](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html#publish-property) that you can use.

**Comment by davecrumbacher** [comment] 2016-03-16 18:06
Thanks for the quick reply, Gary.  Using the AWS SDK for JavaScript publish method works just fine in the Lambda environment.

**Comment by EdwardStanford** [comment] 2016-04-05 01:38
Another sighting on a Beagle Bone Green, Node version v 0.10.29.

Running with -harmony gets past this error, but hits
node -harmony shadow.js

/var/lib/cloud9/examples/Grove_BBG/aws-iot-device-sdk-js/common/lib/tls-reader.js:92
      throw new Error(exceptions.INVALID_KEY_PATH_OPTION);
            ^
Error: Invalid "keyPath" option supplied.
    at module.exports (/var/lib/cloud9/examples/Grove_BBG/aws-iot-device-sdk-js/common/lib/tls-reader.js:92:13)

Any advice appreciated.

**Comment by gkwicker** [comment] 2016-04-07 16:31
Hi Edward, the invalid key path option is letting you know that it can't find your private key.  Can you make sure that you have set caCert, privateKey, and clientCert in the options?  [This section of the README.md](https://github.com/aws/aws-iot-device-sdk-js#api) has more details.  Have a look at that, make sure you have those options set, and if you're still seeing issues make sure to let us know.  Thanks for using AWS IoT.

**Comment by akashkumar25274** [comment] 2016-04-12 06:48
Facing the same issue when trying to run on openshift (Map is not defined).

**Comment by bhadrip** [comment] 2016-04-12 16:14
Hello @akashkumar25274 ,

did the --harmony option help in your case ? Which version of node are you running ?

Thanks
Bhadri

**Comment by jdelaune** [comment] 2016-04-12 17:23
Is there an older version without ES6 in it? I'm getting the "ReferenceError: Symbol" issue on Edison and the --harmony option doesn't resolve it.

**Comment by peterpajchl** [comment] 2016-04-12 17:25
@jdelaune I haven't tried other versions but due to the above issues I am currently using V1.0.5 in my project.

**Comment by typemismatch** [comment] 2016-04-12 17:27
Try npm install aws-iot-device-sdk@1.0.10

**Comment by gkwicker** [comment] 2016-04-12 17:28
@jdelaune,  yes you can install the previous version with 'npm install aws-iot-device-sdk@1.0.10'.  That version doesn't include any ES6 types.  These will be removed from the next release.  Thanks for using AWS IoT.

**Comment by jdelaune** [comment] 2016-04-12 17:33
Great many thanks

**Comment by tsrktty** [comment] 2016-04-14 10:34
It works... `npm install aws-iot-device-sdk@1.0.10`

**Comment by gkwicker** [comment] 2016-04-19 23:25
Fixed in [version 1.0.12](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.12)

**Closed by gkwicker** 2016-04-19 23:25 UTC

**Comment by pushtheworldllc** [comment] 2016-06-06 18:07
I am seeing this in node 5.11.

**Comment by typemismatch** [comment] 2016-06-06 18:23
What version of this package are you using? It needs to be 1.0.12 or greater. For 250Hz you have a 512Kbs limit so keep that in mind too (unrelated).

**Comment by pushtheworldllc** [comment] 2016-06-06 18:26
I'm using `v1.0.12`

**Comment by mansurali901** [comment] 2016-07-12 08:27
This issue is related to your Node version use the appropriate Node version.
The best way is to use NVM to manage your node packages. you can use below commands to rush out from this issue.

[root@ifr4 ~]# wget https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh
[root@ifr4 ~]# chmod +x install.sh
[root@ifr4 ~]# ./install.sh
[root@ifr4 ~]# nvm list-remote
[root@ifr4 ~]# nvm install v0.12.0
[root@ifr4 ~]# nvm use v0.12.0

Regards,
-Mansur
