### ISSUE TITLE
`ReferenceError: Symbol is not defined' will occur with Node V0.10

### ISSUE THREAD

**Issue by Neeil** [aws/aws-iot-device-sdk-js#45] opened 2016-03-23 08:39 UTC
It seems `ReferenceError: Symbol is not defined" will occur in Node V0.10 or V0.11.
Since I update nodejs to 4.4, issue solved.

This remind of the Map not defined issue. So why not added a nodejs version check in the code, so that designer will not confused with version conflict issues.

**Comment by gkwicker** [comment] 2016-03-23 17:53
Hi Neeil, thanks for letting us know about this issue.  We will be removing ES6 types from the next release.  We're going to go ahead and close this as a duplicate of issue #41; if you've got additional comments on this problem, please let us know on that thread so that other users who encounter the same issue can find them easily.  Thanks for using AWS IoT.

**Closed by gkwicker** 2016-03-23 17:53 UTC
