### ISSUE TITLE
Unable to subscribe to IoT Secure Tunnel notify topic

### ISSUE THREAD

**Issue by jmattsson** [aws/aws-iot-device-sdk-js#357] opened 2020-12-09 03:15 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
To use AWS IoT Secure Tunneling one needs to subscribe to the topic `$aws/things/thing-name/tunnels/notify` as per 
https://docs.aws.amazon.com/iot/latest/developerguide/agent-snippet.html. The SDK refuses to allow this and throws the error `cannot subscribe to topic array since one of them is a reserved topic '$aws/things/thing-name/tunnels/notify'` instead.

**SDK version number**
2.2.6 (latest available via npm)

**Platform/OS/Hardware/Device**
Embedded Linux, nodejs 10.15.2.

**To Reproduce (observed behavior)**
Attempt to `.subscribe('$aws/things/thing-name/tunnels/notify')`

**Expected behavior**
The subscription request should be actioned, not rejected.

**Logs/output**
See above.

**Additional context**
Migrating to the aws-iot-device-sdk-v2 is not currently an option.

**Comment by jmklix** [comment] 2020-12-09 18:44
Can you try installing the latest version from github:

> git clone https://github.com/aws/aws-iot-device-sdk-js.git
cd aws-iot-device-sdk-js
npm install

I was unable to replicate this on a raspberry pi zero after modifying the the device-example to subscribe and publish to `$aws/things/thing-name/tunnels/notify`. If using the latest version from github doesn't work can you enable logging and include them with the subscribe error?

**Comment by jmattsson** [comment] 2020-12-10 04:04
Hi @jmklix,

If you're just using the device class you might be fine, but if you're instead using thing shadows and try to subscribe via that class you get hit by the `isReservedTopic()` check on line 732 in "thing/index.js", as that check is overly broad (and pre-dates the Secure Tunneling support, I'd expect). This check is still present in latest master here. Hope that clarifies the issue.

**Comment by jmklix** [comment] 2020-12-10 19:31
If I understand what your trying to do correctly then you shouldn't be using the 'thing shadows'. Shadows are used for storing the device state for access by other apps/services whether a device is connected or not. When trying to store a value in the reserved topic you correctly get an error saying this is a reserved topic because it cannot be used for shadows.

You want to use `$aws/things/thing-name/tunnels/notify` as mentioned [here](https://docs.aws.amazon.com/iot/latest/developerguide/agent-snippet.html) to receive the clientAccessToken. As shown in the device example just use:
```
device.subscribe('$aws/things/thing-name/tunnels/notify');
```

**Comment by jmattsson** [comment] 2020-12-10 23:36
What I'm wanting to do is to:
 - Use the thing shadow as normal
 - Also listen for tunnel notifications
 - On the one MQTT connection

As the [documentation says](https://github.com/aws/aws-iot-device-sdk-js#subscribe), the `AwsIot.thingShadow` provides pass-through functions for pub/sub to the `AwsIot.device` object the shadow class uses internally. This works perfectly fine for most topics. The problem is that `$aws/things/thing-name/tunnels/notify` is misclassified by this SDK as being a thing shadow topic, and therefore gets blocked, incorrectly. At the time that code was written, the Secure Tunnelling feature did not yet exist and the code was therefore, at the time, correct. With the introduction of the tunnel notification under the `$aws/things/` prefix, the code is no longer correct.

Since I'm already having a device shadow object, I do *not* have access to a device object as it's hidden internally within the device shadow object. Having multiple connections open would incur extra costs and is a non-starter. All that needs fixing is that this SDK stops misclassifying the tunnel notification topic as a thing shadow topic.

Changing line 37 in `things/index.js` from
`if (topic.substring(0, 12) === '$aws/things/') {`
to
`if (topic.substring(0, 12) === '$aws/things/'  && topic.substr(-15) !== '/tunnels/notify') {`
would be sufficient I believe.

I hope this clarifies things.

**Comment by jmklix** [comment] 2020-12-15 17:59
Sorry, but this is not something that is dependent on the sdk. This is not allowed by the the IoT service. If you would like further assistance please contact AWS support.

**Comment by jmattsson** [comment] 2020-12-16 01:58
Uhm, beg your pardon @jmklix?
What is not allowed by the IoT service?

To listen for tunnel notification messages, one needs to subscribe to `$aws/thing/ThingName/tunnels/notification`. With this SDK, it works when using the "device" class, but does not work when using the "thingShadow" class because the latter incorrectly classifies the tunnel topic as a thing-shadow topic and therefore, incorrectly, blocks it.

Per the documentation: "The 'thingShadow' class supports multiple Thing Shadows per mqtt connection and **allows pass-through of non-Thing-Shadow topics** and mqtt events." (emphasis mine)

The tunnel notification topic is not a thing-shadow topic even though it starts with `$aws/thing/`. It should be passed through, not blocked.

**Comment by jmklix** [comment] 2020-12-17 16:49
@jmattsson I am checking with IoT product management to get further clarification on what the expected behavior is.

**Comment by jmklix** [comment] 2021-02-22 21:32
Sorry for the long wait, but this should be fixed relatively soon. I can't give any timeline, but I will leave this issue open and make sure to update it once the patch is applied.

**Comment by jmattsson** [comment] 2021-02-22 21:53
Thanks for the update!

**Comment by jmattsson** [comment] 2021-04-16 09:45
Hi, just checking if I've missed an update on this - thanks!

**Comment by jmattsson** [comment] 2021-06-16 07:23
@jmklix any news?

**Closed** 2021-06-16 23:38 UTC
Labels: bug, pending-release
