### ISSUE TITLE
#EDIT - Angular 6 causing a missing packages in your package.json

### ISSUE THREAD

**Issue by XCarle** [aws/aws-iot-device-sdk-js#235] opened 2018-08-14 17:24 UTC
Hi,

as we launched the service we had errors building the project : 

`
ERROR in ./node_modules/aws-iot-device-sdk/common/lib/tls-reader.js
Module not found: Error: Can't resolve 'fs' in '/node_modules/aws-iot-device-sdk/common/lib'

ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
Module not found: Error: Can't resolve 'fs' in '/node_modules/aws-iot-device-sdk/device'

ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
Module not found: Error: Can't resolve 'path' in '/node_modules/aws-iot-device-sdk/device'

ERROR in ./node_modules/aws-iot-device-sdk/device/lib/tls.js
Module not found: Error: Can't resolve 'tls' in '/node_modules/aws-iot-device-sdk/device/lib'
`

In your package.json : 
` "dependencies": {
    "mqtt": "2.15.1",
    "minimist": "1.2.0",
    "websocket-stream": "^5.0.1",
    "crypto-js": "3.1.6"
  },`

Does it miss ref libs in the current version?

**Comment by XCarle** [comment] 2018-08-16 08:34
https://stackoverflow.com/questions/50202948/update-to-angular-v6-module-not-found-error-cant-resolve-fs

**Comment by XCarle** [comment] 2018-08-16 14:54
https://github.com/aws/aws-iot-device-sdk-js/issues/223

**Comment by ColdenCullen** [comment] 2018-08-16 19:49
Closing as duplicate of #223.

**Closed by ColdenCullen** 2018-08-16 19:49 UTC
Labels: duplicate
