### ISSUE TITLE
clientId not sent, or sent differently ?

### ISSUE THREAD

**Issue by alfonsodev** [aws/aws-iot-device-sdk-js#78] opened 2016-08-12 20:45 UTC
Hi, I suspect the ClientId is not sent properly.
I use clientid `mobile_001`
then I can subscribe to the topic:

```
      device.subscribe(`$aws/things/mobile_001/shadow/update`);
```

Because the attached policy is defined with `mobile_001` hardcoded: 

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [  "iot:Connect","iot:Receive", "iot:GetThingShadow"],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource":[
        "arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/mobile_001/shadow/update"
      ]
    }
  ]
}
```

But not when using `${iot:ClientId}` instead of hardcoded `mobile_001` 

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [  "iot:Connect","iot:Receive", "iot:GetThingShadow"],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource":[
        "arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/${iot:ClientId}/shadow/update"
      ]
    }
  ]
}
```

Where the only difference is the use of the variable ${iot:ClientId}
The variable should be replaced with the client id when AWS checks credentials but apparently is not, or the client id doesn't match 'mobile_001'  

The debug information shows the ClientID correctly though 

```
{ clientId: 'mobile_001',
  region: 'eu-west-1',
  debug: true,
  host: 'xxxxxxxxx.iot.eu-west-1.amazonaws.com',
  protocol: 'wss',
  sessionToken: '',
  accessKeyId: '',
  secretKey: '',
  reconnectPeriod: 1000,
  fastDisconnectDetection: true,
  port: 443,
  websocketOptions: { protocol: 'mqttv3.1' } }
```

Any ideas ?

**Comment by chaurah** [comment] 2016-08-17 00:37
Hi @alfonsodev,
I would be happy to help you with this issue. There are a couple of things you can do to check what could be going wrong here.
1) Please ensure the region and the account id are correct in the resource name.
2) Can you check if your code is not doing a publish or any other disallowed operation anywhere else? That could be causing the connection to close silently.

Please let us know if this helps or if we can help you further. Thank you for using AWS IoT.

Rahul

**Comment by alfonsodev** [comment] 2016-08-17 08:44
Hi Rahul,
both checks are good, the proof is that I can `subscribe` when the policy is hardcoded
```
 {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource":[
        "arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/mobile_001/shadow/update"
      ]
}
````
Without problem, I can subscribe and listen to messages and print them on screen.
Now, without changing the code, I change mobile_001 with the variable `${iot:ClientId}`
detaching and attaching the new policy.
```
 {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource":[
        "arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/${iot:ClientId}/shadow/update"
      ]
}
```
The clientId option is set to 'mobile_001' I check in mqtt client and is passed ok to mqtt lib,
but I'm not allowed to subscribe to.  
```
`arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/mobile_001/shadow/update`
```
seems like  the clientId send by mqtt is not replaced by the policy variable ${iot:ClientId}  
or I'm missing something.

**Comment by chaurah** [comment] 2016-08-17 18:10
Hi @alfonsodev,
We tried out your policies as is in both the eu-west-1 and us-west-2 regions. We were not able to replicate the issue unfortunately. Do you have Cloudwatch logs set up for IoT? Can you please check what log entries are created when you run the code with the policy that doesn't work?

I am assuming you are not trying to run one of the samples with this policy. Would it be possible for you to run the device example with this policy enabled? You will need to add "iot:Publish" permission to this policy. Just subscribe to the shadow update topic directly instead of the default one in the sample and check if that still doesn't work. You can modify the topic name [here|https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/device-example.js#L52].

Alternatively, if if is possible for you to share the relevant parts of your code, we can test this out for you.

Please let me know if any of the above suggestions help.

Rahul

**Comment by rongsaws** [comment] 2016-08-18 00:26
@alfonsodev, from the debug information you gave above, it appears you were connecting through WebSocket. I wonder how and where you attached your IoT policy? Were you using Cognito authorized user or non-authorized user to connect?

**Comment by alfonsodev** [comment] 2016-08-18 09:52
Hi @chaurah @rongsaws  I've uploaded an example, 
https://github.com/alfonsodev/aws-iot-example/blob/master/index.js
I'm using Cognito Federated identities, which are working fine, except that it seems I can't get ${iot:clientid}

**Comment by alfonsodev** [comment] 2016-08-18 17:55
And the logs from CoudWatch:

Success when clientid is hardcoded like this.
```
  "Resource":[
        "arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/mobile_001/shadow/update"
      ]
```
I subscribe Successfully 
```
2016-08-18 17:49:27.068 TRACEID:38f46b31-39c6-b7b0-78b9-f36d6501f6f3 PRINCIPALID:xxxxxxxxxxxx/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials [INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: SUCCESS
2016-08-18 17:49:27.309 TRACEID:fe1e6c42-33c3-9073-9a9b-587debe90337 PRINCIPALID:xxxxxxxxxxxx/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials [INFO] EVENT:MQTTClient Subscribe TOPICNAME:$aws/things/mobile_001/shadow/update MESSAGE:Subscribe Status: SUCCESS
```

Error when  ${iot:ClientId} var is in  the directive like this
```
    "Resource":[
        "arn:aws:iot:eu-west-1:xxxxxxxxxxxx:topicfilter/$aws/things/${iot:ClientId}/shadow/update"
      ]
```
Client error on subscribing 
```
y016-08-18 17:46:03.651 TRACEID:3e93dcaf-ea2d-a523-83fa-4fea4131333a PRINCIPALID:xxxxxxxxxxxx/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials [INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: SUCCESS
y016-08-18 17:46:03.716 TRACEID:611cc5a0-16b8-ac15-0374-c124f2b82d4f PRINCIPALID:xxxxxxxxxxxx/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials [INFO] EVENT:MQTTClient Subscribe TOPICNAME:$aws/things/mobile_001/shadow/update MESSAGE:Subscribe Status: CLIENT_ERROR
y016-08-18 17:46:06.151 TRACEID:180a4a89-7367-b244-a40c-a5c29e16a9c0 PRINCIPALID:xxxxxxxxxxxx/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials [INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: SUCCESS
y016-08-18 17:46:06.212 TRACEID:0de213de-2890-fecc-dff2-6a8a31beaab3 PRINCIPALID:xxxxxxxxxxxx/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials/YYYYYYYYYYYYYYYYYYYYY:CognitoIdentityCredentials [INFO] EVENT:MQTTClient Subscribe TOPICNAME:$aws/things/mobile_001/shadow/update MESSAGE:Subscribe Status: CLIENT_ERROR
```

**Comment by alfonsodev** [comment] 2016-08-18 18:07
Another information, when using Cognito there is a Role created named Cognito_myappAuth_Role , 
I attach to this Role only all IoT policies 
```
 AWSIoTLogging
 AWSIoTConfigAccess
 AWSIoTRuleActions
 AWSIoTConfigReadOnlyAccess
 AWSIoTDataAccess
 AWSIoTFullAccess
```
Just in case is relevant information

**Comment by rongsaws** [comment] 2016-08-18 22:44
Thanks for providing detailed information. We were able to reproduce the same error on our end. What we also found was this issue only affects one use case, which is when the clientId variable is used in a policy attached to authorized Cognito identities.  For non-Cognito based principals and non-authorized Cognito roles, the clientId variable can be correctly evaluated.

Since this is a backend bug, we have forwarded it to the relevant team, who has acknolwded this issue and already started working on a fix for it. 

We apologize the incontinence caused. Please feel free to let us know if there's anything else we could help. Thank you.

**Comment by alfonsodev** [comment] 2016-08-19 08:49
Thanks for short time response, I'm glad that I could help.
It would be great if the backend team could add support for  ${aws:userid} var in IoT policies.
Currently seems that IoT policies only support two variables, ${iot:ClientId} and ${aws:SourceIp} 
with ${aws:userid}  I could a Thing per user and not per ClientId so one iOS device and another Android device belonging to the same user, could subscribe to the same ${aws:userid}/shadow/update.
Where can I suggest this improvement ?
Thanks.

**Comment by rongsaws** [comment] 2016-08-22 17:38
I guess you were referring to Cognito Identity Id that you want to use instead of client Id? If that's the case, you can use this variable in your policy **${cognito-identity.amazonaws.com:sub}**. You can find more details here http://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html in the Cognito documentation.

**Comment by mmadjer** [comment] 2016-10-03 04:55
I have the same issue, is there any update on this one?

Thanks.

**Comment by rosenk** [comment] 2016-12-15 11:34
@rongsaws Please help. I'm trying to partition Iot access with Cognito

Currently I have the following policy which almost does the trick:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["iot:Connect"],
      "Resource": ["arn:aws:iot:eu-west-1:929242459730:client/${iot:ClientId}"]
    },
    {
      "Effect": "Allow",
      "Action": ["iot:Subscribe"],
      "Resource": ["arn:aws:iot:eu-west-1:929242459730:topicfilter/myapp/${cognito-identity.amazonaws.com:sub}/*"]
    },
    {
      "Effect": "Allow",
      "Action": ["iot:Receive"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["iot:Publish"],
      "Resource": ["arn:aws:iot:eu-west-1:929242459730:topic/myapp/${cognito-identity.amazonaws.com:sub}/*"]
    }
  ]
}
```


but unfortunately I still need to attach every individual user from the identity pool as a principal to this policy. I'm trying to make this universal, so when a new user registers she automatically gets access to communicate with her own things. 

Please help, how to make the policy universal? I'm trying to avoid having custom registering procedure after each customer registration just to add it as principal in this otherwise universal policy.

**Comment by fengsongAWS** [comment] 2017-11-06 23:33
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Closed by fengsongAWS** 2017-11-06 23:33 UTC
