### ISSUE TITLE
"Report only" variables and the shadow's Delta topic

### ISSUE THREAD

**Issue by tai-x** [aws/aws-iot-device-sdk-js#160] opened 2017-10-27 23:19 UTC
Hi everyone. I am currently programming an embedded system using AWS IoT for device-app synchronization, and soon enough I found myself with some "report-only" variables, variables which only have one single source of truth. I.e. a value read from a sensor, which conceptually makes sense to only write as "reported" in the shadow.

Concrete example: the ambient temperature in a thermostat is something that makes sense to keep in the "reported" section of the shadow, but not in the "desired". And the app is interested on knowing of changes to this value to paint a screen.

It turns out that most implementations handle shadow synchronization using a callback on the "update/delta" topic in particular (we know there are other handy shadow topics but in reality it is strongly based on the "delta"). Put simple, if you want to know that there was a change in a variable: delta will tell you; with some limitations: http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html?shortFooter=true#update-delta-pub-sub-topic

This limitation in particular addresses my concern:

> If an attribute is in the reported section but has no equivalent in the desired section, it is not included.

This means that a very common use case scenario, e.g. an app wanting to know if a "report only" variable changed (like ambient temperature in a thermostat), cannot use the delta topic for this purpose because the variable is not present in the "desired" section (so messages in the delta topic won't be triggered),

What's the recommendation here? Should we subscribe to both to the "update/delta" and "update/accepted" topics? - this adds complexity. Or, could we just write both "desired" and "reported" to get away with it? - this would force messages in the delta topic when there is a change in the variable; although it doesn't seem ok to write "desired" values on a "report-only" variable.

I think conceptually there is a gap here in the AWS IoT shadow topics definition, for a very common IoT shadow use case.

**Comment by fengsongAWS** [comment] 2017-10-30 18:04
I think the device should always publish to `desired` state of shadow document. The corresponding reported section should only be updated once the device or monitor catches messages from `delta` topic. This is to make sure the shadow documents will always be in sync. 

I think the correct way is to subscribe to `upate/delta` and `update/accepted` topics. You can take a look at the temperature-control.js example to see if it can help you because I think you have very similar use case demonstrated there.

Thanks

Thanks

**Comment by tai-x** [comment] 2017-10-30 20:01
I confirm that having the device update the "desired" state of the "report-only" variable works. But it feels I am doing this just to have a message triggered in the delta topic. Conceptually my variable only needs to be "reported".

About:

> The corresponding reported section should only be updated once the device or monitor catches messages from delta topic. 

No. Because I don't want the variable inside my device to respond to any "desired" state changes coming from the shadow (for which the source of the change may not be clear). If someone else (like an app) publishes a "desired" state to this variable, the device should ignore it because the device is the single source of truth for this variable. I am currently just updating the "desired" and "reported' state of the variable from the device, and within the device ignore anything coming in for this variable in the delta callback.

Like I said, I think the limitation of the delta topic that requires both desired/reported states on a variable complicates this (rather common) scenario.

**Comment by Fahrenheit2539** [comment] 2017-10-30 20:40
I'm trying to understand how does using delta topic help here.

As it is delta between desired and reported (and not between current and previous value), I don't see how it is different from subscribing to the whole document updates.

Can you elaborate?

**Comment by fengsongAWS** [comment] 2017-10-30 20:48
@tai-x ,
When each time there is an operation, a token generated from the device will be included in that packet. So, to tell the source of the operation, you can track the token to tell the source and hence can ignore the others. Alternatively, the IoT policy can also help on restricting devices on performing operations but this is another story. 

@Fahrenheit2539 , The `update` topics were added sometime later than the concept of `delta`. By subscribing the whole document updates could also do the trick. It just depends on the different customer use cases and preference.

**Comment by tai-x** [comment] 2017-10-30 21:10
@fengsongAWS 
I'm sort of trying to make you guys at AWS reflect on the design of the AWS topics behavior and definition. E.g. the "token" solution, I can't tell if I can easily obtain the client id from the library and send it to the callback. For instance, will it make sense to include the "client id" in the metadata of the variable?

@Fahrenheit2539 
For a "report"-only variable like ambient temperature, even the "current" concept doesn't apply very well, it just the last known. I get tho that using update/accepted or update/documents can do the trick.

-
I'm also trying to bring into consideration that most implementations, both in the device and app side, will tend to be based on the "delta" topic, for synchronization simplicity.

**Comment by fengsongAWS** [comment] 2017-10-30 21:48
@tai-x ,

Conceptually, the design of shadow is more of like the device or remote controller should always post their value to a `desired` state, and when the device itself catch the desired to be value, it should update its `reported` value to be sync with `desired` value. And when next update happens, it will do the same thing. 

To answer your second question. An update could be caused by either the "device" it self or a "remote controller". The token generated by the client is attached in the shadow document and received by the listeners. This token is used to differentiate who initiated this update. So, as the device, you can store the local copy of client token and compare it with the one you received. If they match, that means it is performed by itself. (https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/thing-passthrough-example.js#L141)

**Comment by tai-x** [comment] 2017-10-31 01:50
@fengsongAWS 
When I started using AWS IoT, I understood the desired/reported flow as you explain. It is completely natural that _remote controllers_ update the `desired` state, and then the _device_ subscribed to the delta topic will respond updating the `reported` state.

This even makes sense for a local change (within the _device_) to a variable that is shadowed and represents a value that is both controlled within the _device_ and by a _remote controller_, i.e. a local button press in the _device_ and a remote action in the _remote controller_ that are handled by the same variable. It makes sense that the device updates the `desired` state as well, and then the `reported` state. I've already implemented this, but works like a charm. [1]

What is not natural though, is a _device_ updating it's `desired` state and then listening to its own message in the delta topic for a variable where the _device_ is the single source of truth. Not the _device_ and not even the _remote controller_ cares about the `desired` value of this variable. They both just want to know what is the `reported` state of the variable. Updating `desired` in this case is just a trick to get a message in the delta topic. I don't think that you would do this because it was designed to be this way. The AWS IoT seems flexible enough to not exactly enforce it (e.g. I can successfully store variables with only `reported` states). Furthermore, the device has to do the special action of checking the client's id in the token for this particular variables, so it will successfully ignore updates that doesn't come from itself.

I guess the cleanest solution is to accept that the delta topic has a limitation that didn't took into account a common use case. **It would have been much easier if messages where sent to the delta topic for changes on variables that only have a `reported` value**. And forcing to either go through this unnecessary desired/reported flow for these type of variables, or add more logic to the _remote controller_ to also listen to the _accepted_ or _documents_topic (whatever works best for the case).

Regarding obtaining the client id from the token, I feel it more internal to the library and not natural in application code. The timestamp in the metadata answers the question of "when", the client id would answer the question of "who". It's convenient to have it there and not just in the tokens from the messages propagated by the broker. If it makes sense to consider for a future versions of the shadow document....

To give closure, regarding our implementation, we had the _device_ update its `desired` state and `reported` state right after the variable change, and just ignore whatever comes from the delta for this variable. Works, and allows the _remote controller_ (an app) to be subscribed just to the delta topic, reducing complexity.

Thanks a lot for your insights, we can continue chatting on this one, but you can close the issue whenever you want. Thanks again.

[1] As a side note, this scenario was a bit tricky since there is a delay in this flow (small, I know, but could be up to 1.5 sec) between when the _device_ updates the `desired` state and receives the message in the delta to update `reported`. During this period the user could continuously change the variable locally (pressing a button repeatedly), or also receive an update from the _remote controller_. It was possible to coordinate nicely, but tricky.

**Comment by fengsongAWS** [comment] 2017-10-31 17:43
Thanks for your interest and comments in AWS IoT. This goes more of towards the design of shadow service and shadow service also keeps adding new logic and functionality e.g. update API. We are more than happy to take more customer use cases. I will close this issue for now and feel free to open another thread if you have more questions on AWS IoT Device SDK.

**Closed by fengsongAWS** 2017-10-31 17:43 UTC
