### ISSUE TITLE
Connection lost every 2-3 Minutes by some users

### ISSUE THREAD

**Issue by GermanBluefox** [aws/aws-iot-device-sdk-js#251] opened 2019-01-23 17:38 UTC
Some of the users (not all) facing the problem, that connection being lost every 1-3 Minutes.
I checked the logs and monitored the activity of specific users and could not see any errors except that disconnection appears and then in 6-8 seconds comes reconnect.... and in i-3 Minutes again disconnect and so on.

What it can be?

It looks like (may be) the client does not answer heartbeat, but is not clear, because no debug info is visible.
How can I investigate why it's happen? I need help.

Regards, Bluefox

**Comment by gauthamkantharaju** [comment] 2019-02-06 19:36
Even we are facing the same issue but in our case client is getting disconnected every 10-15 minutes and reconnects within few seconds.

receiving, **Error: read ECONNRESET** 

Have created a issue in AWS support also but they responded back saying that the issue might be because of firewall or network issue.

**Comment by justinboswell** [comment] 2019-02-06 22:17
Have you tried wireshark (or ssldump) capturing the connection? See if you get a TLS alert as your last packet from the server, or if you time out. If you time out, then there's something going on on your network. If you're getting a TLS alert, then the server is hanging up on you because your last request was malformed or against your policy.

**Comment by GermanBluefox** [comment] 2019-02-08 09:09
Will check it. Thank you.

**Comment by gauthamkantharaju** [comment] 2019-02-08 15:06
@GermanBluefox Any luck?

**Comment by 20matan** [comment] 2019-02-24 16:28
Hey, i had the same error.
Not sure if it's the same case, but in my case it happened because some of the clients had the same clientId. i'm not sure what method you use to generate the clientId, but you should try (in case you don't already) uuid / something similiar that will not result in collisions.

**Comment by GermanBluefox** [comment] 2019-03-02 20:26
> Hey, i had the same error.
> Not sure if it's the same case, but in my case it happened because some of the clients had the same clientId. i'm not sure what method you use to generate the clientId, but you should try (in case you don't already) uuid / something similiar that will not result in collisions.

In case of the same clientID I see on the server the corresponding error. 
In this issue I see only "disconnected" without explanation what is that.

**Comment by h3w8529** [comment] 2019-03-05 18:03
just create another clientID, this clientID is not able to share on different devices.

**Comment by Apollon77** [comment] 2019-03-05 18:50
I think Bluefox said that the clientIds are unique.

**Comment by ColdenCullen** [comment] 2019-03-11 17:23
A couple other things you could check:
1. Does your policy explicitly allow everything you're doing? If you violate it, the server will hang up on you with no indication as to why.
2. Are you hitting any of the [limits](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot) imposed by the service? This would also cause a hang up with no error reported.

**Comment by ToTXR4Y** [comment] 2019-03-29 19:28
I have the same issue, it reoccurs exactly every 4 minutes.

**Comment by Apollon77** [comment] 2019-04-01 13:51
@ColdenCullen We are not aware of any of the questions, so I would state for now "no we don't/everything is correct" ;-)

Do you hve any idea how we could track that down? It is very anoying for some of our users!

**Comment by GermanBluefox** [comment] 2019-04-02 18:02
> A couple other things you could check:
> 
> 1. Does your policy explicitly allow everything you're doing? If you violate it, the server will hang up on you with no indication as to why.
> 2. Are you hitting any of the [limits](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot) imposed by the service? This would also cause a hang up with no error reported.

Which kind of limits it could be be IoT Core?

**Comment by graebm** [comment] 2019-04-25 17:54
[Limits for IoT are listed here](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot)

There are limits on **all** sorts of things. For example, publishing more than 100 messages per second will get you hung up on. Could this be your issue?

**Comment by graebm** [comment] 2019-04-25 18:01
@GermanBluefox 
Are you using a Node.js environment? Or browser environment?

**Comment by graebm** [comment] 2019-04-25 18:34
Are you using websockets to connect? Or direct MQTT?

**Comment by Apollon77** [comment] 2019-04-26 06:47
We are using nodejs environment and because we are using exactly this package here it should be MQTT ;-)

For the limits, ok this is interesting but documentation states e.g. for "more then 100 publishs per second": ... rest will be discarded ... so it should not be the case that the whole connection gets killed. ;-) Or do I missed something?

**Comment by GermanBluefox** [comment] 2019-04-29 15:37
As Apollon77 sad, we use node.js with mqtt and we deliver voice commands (JSON) with IoT. 
If you know someone who can produce more than 100 commands per second, let me know ;)

To be serious, even if no commands sent, the disconnect happens every X minutes.

**Comment by Laudings** [comment] 2019-05-21 21:31
I have the same issue. Are there already some new information?

**Comment by justinboswell** [comment] 2019-05-22 16:48
@Apollon77 When you hit service limits, especially within the IoT Core services, the response is almost always to hang up. I know for sure (due to our unit tests) that IoT hangs up if you break the 100 publishes/sec limit.

**Comment by Apollon77** [comment] 2019-05-22 19:20
Thank you ... this should really not be the case, but maybe @GermanBluefox maybe introduce some kind of counters for logging purposes?

**Comment by klotzma** [comment] 2019-06-12 09:56
Hei, i have the same Problem, it comes all 4 Minutes.

**Comment by Laudings** [comment] 2019-06-21 14:47
I and a lot more user still have the problem. Is it possible to check if it send more than 100 massages per second?

**Comment by Karsten69** [comment] 2019-06-26 05:35
Good morning,

until yesterday everything works fine without any issue. Until yesterday i have a internet connection from Unitymedia (Office and Internet 150) with a Fritzbox 6490 cable as modem and a Fritzbox 7490 as router.
Yesterday i became a new internet connection also from Unitymedia (2play 400) with a Unitymedia ConnectBox as modem and the Fritzbox 7490 as router, the router is the same like before, every other stuff is the same like before. But now i have this issue. Is it possible that the connect box from unitymedia is the problem?

**Comment by justinboswell** [comment] 2019-06-26 18:07
If you are able to establish a connection, but the connection is dropping, I would suggest opening a ticket with IoT Core support, so they can help diagnose further, as it is unlikely to be an SDK-specific issue.

**Comment by Fab29-690** [comment] 2019-06-27 20:09
I got the same error when I changed the internet provider to unitymedia. I use also the connectbox and i have also the same connection 2play400. I think the connect box could be the issue or maybe that you have switched to a new modem ? Or its just a coincidence?

**Comment by Karsten69** [comment] 2019-06-28 12:03
I don't believe that it is a coincidence, i can go back to the old connection with the FritzBox 6490 cable and the Office and Internet 150 to see if it works without the issue. But in the moment i can't try the new connection with a FritzBox. I try it now and write the result later.

**Comment by Karsten69** [comment] 2019-06-28 12:28
With the old connection everything is fine i have no issues. But where is the problem? Connectbox or differences between business and normal tariff from unitymedia, any ideas?

**Comment by Karsten69** [comment] 2019-06-28 12:35
@Fab29-690 i'am not only changing the modem, i have a complete new cable from Unitymedia, but it's in the same Street, the old connection was in my neighbors house, that's why i can switch back to the old connection so easy, this one will work till 05.08.19.

**Comment by Karsten69** [comment] 2019-06-28 13:45
@GermanBluefox 
Hi Bluefox, the issue is reproducible, i can switch between two diferent internet connections, one works without this issue, the otherone with. Will it be helpfull, that you take a look at the debug and i switch between the connections?
Regards
Karsten

**Comment by Apollon77** [comment] 2019-06-28 14:45
Cool and interesting ... but this brings me to one conclution: It can not be the number of messages as assumed above ... because the "Iobroker instance" is the same. So it need to be an connection issue :-(
@justinboswell do yoiu have detailed contact informations for IoT Core support?

**Comment by Karsten69** [comment] 2019-06-28 15:13
hi apollon77, let me know if you need any help or more information. I Think the problem is the ConnectBox from Unitymedia, but i'am not realy shure, and till now i can't check the new connection with a Fritzbox cable.

**Comment by justinboswell** [comment] 2019-06-28 17:33
The IoT Core service support is the same as any other AWS Service, information can be found [here](https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html). In this case, getting wire logs will help diagnose which messages are making it to the service, and which are being dropped/aborted by the network in between.

**Comment by justinboswell** [comment] 2019-06-28 17:34
Given that this is not an device SDK-specific issue, I'm closing the ticket.

**Closed by justinboswell** 2019-06-28 17:34 UTC
Labels: confusing-error

**Comment by Apollon77** [comment] 2019-06-28 18:49
@Karsten69 can you catch the traffic for both cases using wireshark ?

**Comment by Karsten69** [comment] 2019-06-28 20:07
Yes but i need help. Tomorow teamviewer?
Or a few lines howto?

**Comment by Karsten69** [comment] 2019-06-28 20:42
Hallo Ingo,

 

ich glaube wir können Deutsch sprechen :)

Ich habe gerade einen Mitschnitt gemacht vom Raspberry zum Router, allerdings nicht vom Router zum Modem, bis der Fehler aufgetreten ist.

Schau dir das mal an, wenn es das ist was du brauchst mache ich morgen noch einen Mitschnitt mit meiner alten Internetleitung.

Leider weis ich nicht wie ich den Verkehr zwischen Router und Modem mitschneiden kann.

 

Gruß

Karsten


 

Gesendet: Freitag, 28. Juni 2019 um 20:49 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: aws/aws-iot-device-sdk-js <aws-iot-device-sdk-js@noreply.github.com>
Cc: Karsten69 <k.buerger@email.de>, Mention <mention@noreply.github.com>
Betreff: Re: [aws/aws-iot-device-sdk-js] Connection lost every 2-3 Minutes by some users (#251)


@Karsten69 can you catch the traffic for both cases using wireshark ?

**Comment by Fab29-690** [comment] 2019-07-01 14:49
Hallo ihr,

gibt es schon Neuigkeiten bzw. neue Erkenntnisse?

**Comment by Apollon77** [comment] 2019-07-01 15:19
@Karsten69 Attachments werden bei email antworten von GitHub nicht übernommen. Musst Du hier hochladen ... :-(

**Comment by Karsten69** [comment] 2019-07-01 15:35
Ah, ok. Habe mittlerweile herausgefunden wie ich den kompletten verkehr mitschneiden kann, werde es heute aber nicht mehr schaffen. Morgen werde ich dann auf beiden Leitungen mitschneiden und dann hier hochladen. Gruß Karsten

**Comment by Karsten69** [comment] 2019-07-03 08:37
@Apollon77 Hallo Ingo, habe die Dateien fertig, kann ich dir irgendwo eine PN oder Mail schicken, würde ungern meinen ungefilterten Datenverkehr hier für alle sichtbar einstellen. Im IOBroker Forum habe ich schon gesucht aber keine Möglichkeit gefunden dir eine PN zu schicken.
Gruß Karsten

**Comment by Apollon77** [comment] 2019-07-03 08:46
iobroker@fischer-ka.de

**Comment by Karsten69** [comment] 2019-07-03 09:02
@Apollon77  Ist raus.

**Comment by GermanBluefox** [comment] 2019-07-03 13:24
So. I analysed the wireshark and could see, that the disconnect comes from AWS IoT side after 2:23 seconds of silence.
Here is the communication: 
[ioBroker IoT mqtt communication.zip](https://github.com/aws/aws-iot-device-sdk-js/files/3355134/ioBroker.IoT.mqtt.communication.zip)
@justinboswell And reset is from IOT:
![image](https://user-images.githubusercontent.com/4582016/60595081-99ae9c00-9da6-11e9-8b76-5b6cc7b78b3a.png)

**Comment by Karsten69** [comment] 2019-07-28 12:21
Hallo Leute,

ich kann leider die ConnectBox von Unitymedia ausschließen, habe Heute auf Fritzbox 6490 umgestellt und der Fehler kommt weiterhin.

Schönen Sonntag noch.
Gruß Karsten

**Comment by klotzma** [comment] 2019-07-28 12:41
Das kann ich übrigens auch bestätigen, ich habe schon seit längeren meine eigene Fritzbox 6490 über den Anbieter Unitymedia.
Trotzdem diese Probleme

LG Marcus

**Comment by Fab29-690** [comment] 2019-07-28 13:09
Was ich mir nochvorstellen kann ist, dass das Problem mit dem DS und DS-lite was zu tun hat. Ich habe leider nur DS-Lite und wäre interessant, ob einer von euch DS hat.
Lg

**Comment by Karsten69** [comment] 2019-07-28 16:42
Ja kann gut sein, hatte vorher Unitymedia Business Office und Internet 150, das war kein DS-lite, aber was genau kann ich nicht mehr sagen. Jetzt habe ich definitiv DS-lite. Vieleicht können die die keine Probleme haben mal nachschauen was bei ihrem Unitymedia Anschluss anliegt. Habe allerdings keine Ahnung ob das zur Problemlösung beiträgt.

Gruß
Karsten

**Comment by ToTXR4Y** [comment] 2019-07-28 16:45
Liegt weder an DS-Lite noch an DS bei Unitymedia. Ich hatte das Problem (siehe weiter oben) ebenfalls. Interessanterweise hat es sich bei mir beim Update vom Alexa Adapter von alleine gelöst bzw. hatte ich parallel das ioBroker Fixer Script zum korrigieren von etwaigen Berechtigungsfehlern zwischendurch ausgeführt.

**Comment by klotzma** [comment] 2019-07-28 16:51
Ich nutze aber nicht mal Alexa, sondern nur IFTTT und seit neusten Google Home.
Trotzdem diese Verbindungsabbrüche.
Fixer habe ich auch schon laufen lassen.

**Comment by Apollon77** [comment] 2019-07-28 18:45
Alexa adapter update or permission fixes should have no effect here. Also this is used independently from Alexa or google home because it is the basic cloud service

**Comment by Fab29-690** [comment] 2019-07-29 14:38
Hallo ich glaube ich hab des Rätsels Lösung.
Ich habe mich aus einem anderen Grund von DS-Lite auf Dual Stack umstellen lassen und seit dem habe ich keine Verbindungsabbrüche mehr. Ist zwar erst eine halbe Stunde her und werde es noch weiter beobachten.

**Comment by klotzma** [comment] 2019-07-29 15:42
Ich kann mir net vorstellen das es am DS Lite liegt, jeder andere Cloud service geht  doch auch unter den DS Lite Anschluss.
Da ist doch irgentwas anderes Faul.

**Comment by Fab29-690** [comment] 2019-07-29 15:48
Ich hab definitv nichts anderes geändert. Vor der Umstellung war definitiv noch das Problem vorhanden und nach der Umstellung sofort weg. Also bei mir hat die Umstellung das Problem verschwinden lassen.

**Comment by klotzma** [comment] 2019-07-29 18:19
Ja gut, aber ich zum Beispiel habe nicht die Möglichkeit ein Dualstack Anschluss zu bekommen, außer ich wechsel mein Vertrag und ich denk mal da bin ich nicht der einzigste. 
Da muss es doch eine andere Lösung geben.

**Comment by klotzma** [comment] 2019-07-29 18:25
Ich kann den Iot Service, seit dieser permanenten Abbrüche kaum noch verwenden. Weder über die direkte Google Home Anbindung noch über den Umweg über IFTTT.

**Comment by Karsten69** [comment] 2019-07-30 08:21
Guten Morgen,

ich kann jetzt bestätigen das es an DS-Lite liegt, habe meinen Anschluss gerade auf Dual Stack umstellen lassen und der Fehler ist weg. Ich habe bei UM angerufen und hatte direkt eine sehr freundliche und kompetente Mitarbeiterin am Telefon, die genau wusste wovon ich spreche, die Umstellung erfolgte noch während des Telefonates und seitdem habe ich keine Fehlermeldungen mehr.
UM stellt die Anschlüsse wohl nur auf Nachfrage Kostenlos um wenn man schon ein Zusatzpaket, in meinem Fall die FB6490, hat.
Gruß Karsten

**Comment by Karsten69** [comment] 2019-07-30 08:33
Noch kurz zur Info, reines IPV4 gibt es dann aber nur in den Business Verträgen.

**Comment by Laudings** [comment] 2019-07-30 10:42
Hallo,

Das hört sich sehr interessant an. Kann wir aber jemand erklären was ds-lite ist und was Dual Stack ist? Habe ich noch nie gehört. Was ist der Unterschied dieser beiden?

Vielen Dank! 

Grüße Swen

**Comment by ToTXR4Y** [comment] 2019-07-30 13:52
DS-Lite = ipv6 Anschluss mit getunnelten IPv4 (öffentliche IPV4 Adresse für mehrere Teilnehmer)
DS = Dual Stack -> echte IPV4 und echte IPV6 Adresse für den eigenen Anschluss

Reines IPV4 bekommt man bei Unitymedia mit Tariferweiterung auf "Power-Upload" und gleichzeitig den Wunsch äußern das man einen nativen Dual Stack bekommen möchte. Kostet glaube ich, je nach Region, 2.99 Euro zum normal gebuchten Tarif monatlich extra.

Aber wiegesagt, das sich das Problem "aufgelöst" hat durch Umstellung auf DualStack (also echte IPV4/IPV6) ist unrealistisch, sondern ist vermutlich einfach nur dem geschuldet das sich das System mit einer "neuen" IP meldet in der Cloud. Bei den DSLite Anschlüssen hat man ja mitunter mehrere Wochen diesselbe IP trotz Neustart.

Ich kann nur betonen, ich habe den IoT an beiden Anschlüssen laufen, sowohl Lite als auch echtes DS.

**Comment by klotzma** [comment] 2019-08-31 15:33
Kann mir hier jemand weiterhelfen einen Mitschnitt, mit Wireshark zu machen ?
Ich komme nicht so zurecht damit.

Bezogen auf diesem Issue [# 230](https://github.com/aws/aws-iot-device-sdk-js/issues/280)

**Comment by Apollon77** [comment] 2019-09-11 06:56
For affected users check solution https://github.com/aws/aws-iot-device-sdk-js/issues/280#issuecomment-529990098
